// Article data for Abide
window.ABIDE_ARTICLES = [
  {
    id: "he-must-become-greater",
    number: "01",
    category: "Intimacy",
    title: "He Must Become Greater",
    subtitle: "On spiritual gifts, attention, and the shift from self-glory to His glory",
    verse: "John 3:30",
    author: "Bible Study Group",
    date: "April 21, 2026",
    readTime: "9 min",
    hero: "./uploads/wk1.png",
    excerpt: "God doesn't just want to use us — He wants to give us Himself. A recap of this week's gathering.",
    raw: `They keep coming back to the same center: God wants His people to experience His presence. Not just know about Him, not just operate in gifts, not just be useful. Presence. Intimacy. That's where this starts.

One of the first things shared is how this has actually been working out in real life. There's this description of being around someone and suddenly sensing an overwhelming depression on them. Sometimes that leads to going directly to the person, asking a few questions, praying for them. Other times it feels like something to carry privately, praying alone, praying in the Spirit, not drawing attention to it. And then there are moments in prayer where the person isn't even praying about that situation at all, and suddenly gets a vision or an insight into what is on God's heart, not their own. That phrase lands: what is on His heart, not mine.

A concrete example gets given. In prayer, while focused on something else entirely, there's suddenly a picture of a specific church, and specific people in that church that God wants to show love toward, stir up, and turn back to Himself. The response in the moment is immediate prayer for those people. The thought underneath it is that the more time someone spends with God, the more He can trust them with what He wants to do, because they actually want to be part of His work.

Then it moves into blessing and gifts and reward, but not in a triumphalist way. The point being made is that God does bless materially, because He is a good Father. There's an image of a dad and candy and a child, and how of course a father gives gifts, but what he actually wants is closeness, intimacy, relationship. It would break his heart to give things and never be known. Even so, he would still give. Grace comes up there. The deeper point is that God will bless, and He will use people, because His will is going to happen, but what He really wants to give is Himself. That only happens in intimacy, where trust is possible.

That leads into one of the clearest personal confessions in the whole meeting. The relief is that the gifts don't originate in the person. If they did, then everything would rest on them: when to use them, how to use them, whether they succeed. That sounds like anxiety immediately. There's almost a recoil from the idea of having spiritual power as a possession. The better thing is just wanting to be part of what the Father is doing. Then the weight comes off. It's His words, not mine. And then the confession gets even more direct: six months ago, the only thing coming out of the mouth was basically, how do I build a platform for myself so people will see me and I'll be glorified. Now the question is, how can I be part of what the Father is doing? How can I become less and He become more? There's a sense that every word now is meant to glorify Jesus. The speaker says their whole life has been about self-glorification and that it broke God's heart. They say they don't want that anymore. That moment lands hard.

Then someone else shares a story that confirms the whole idea. A cousin had prayed that if God wanted her to encourage anyone or give someone a word, He would tell her. After church she came over, nervous, anxious, unsure of herself, and said what she felt prompted to say: "You are seen and you are loved." What she did not know is how deeply that hit in that exact moment, right before the service. It's remembered as perfectly timed. The conclusion is simple: that is powerful, and that is exactly the kind of thing being talked about. No accidents. God uses broken vessels. That line gets expanded too: He works through broken vessels all the time, even people turned away from Him, even people who know they are turned away from Him. He can still use them. It doesn't matter who you are.

### A Loved One, and the Question Under It

Then the conversation turns toward a loved one in someone's family — a mom who's sick — and the emotional temperature shifts. Someone says all they can think about is her, and it's breaking their heart. The question starts forming around healing, around why it doesn't seem to work the straightforward way people imagine it should. The picture in mind is simple and direct: someone could go to the hospital, pray over her, and she'd be healed. Why doesn't it work like that? And if it doesn't, is it because this suffering is somehow being used to pull on hearts — on her son, on the family, on her husband — so that something larger happens through it? There's uncertainty in the way it's asked. It's not a statement so much as a question pushed out into the room for help.

The immediate response is practical and sobering: what if you pray and ask God if that's what He wants you to do? Someone says they already did and didn't have peace about going. Another person admits they thought the question was going in a different direction — toward whether her condition is because she is living a certain way — and rejects that outright. But the question stays where it began: why doesn't healing just happen the way we want it to, and could God be using this pain for something more?

One answer is short: that is above our pay grade. But then more gets said. His will is going to happen. He is healing. He doesn't just hand out a random bag of healings. There is a strong insistence that she and her family — her husband and her kids — need to believe she is healed, has already been healed, because Jesus already took it on His back. He already dealt with death and sin. The language gets intense there: they need to believe, they need to lay hands on her, they need communion, they need their eyes on the blood and body of Jesus.

But the original questioner keeps pressing the point they were trying to make: the ailment itself could be working for the Lord by affecting the family in a certain way. Not just the healing, but the suffering around it. Someone else picks up Matthew 8 to bring scripture into it. The leper asks Jesus, "If you are willing, can you heal me and make me clean?" Then the centurion asks healing for his servant, and Jesus says He'll come, but the centurion says He doesn't need to come physically, just say the word and the servant will be healed. The point seems to be that healing is clearly in Jesus' authority and willingness, but the tension in the room remains.

Another person says this exact question has been difficult for them too because of a loved one's blindness. They tell the story: she started out cross-eyed when she was very young, and over time lost all vision in one eye. There's bitterness because her mother didn't take her to a doctor when there may have still been vision to preserve. There's been prayer for healing for years. That prayer hasn't gone away. But the speaker says they think there's more to it, more God can do in someone and through someone and around someone because of those conditions, even though they don't know exactly what. They've heard stories. Maybe healing still comes later. But the struggle is real and it sounds very close to the same question.

Then comes one of the longest and heaviest responses of the night. First: nobody has the full answer, and to think we do would probably be heresy. Then: Christ's body was broken so that we might be healed. There is power there beyond what is understood. It is God's will that all be healed, and also His will that all be saved. Asking why people are not healed is compared to asking why some people do not come to Jesus, or why bad things happen in the world. Then comes the correction: we let sin into this world, not Him. Jesus came down into flesh. The Creator became creation because only the Creator can redeem and restore creation. He had to die. A will does not go into effect without death. Covenant is not made without shedding blood. So suffering and death are not side issues in the Christian story. They are central. It was the will of the Father to crush Him.

And then the room is brought right into the present: suffering is guaranteed. The consequences of sin in the world are real. But what Jesus promises is His presence in the midst of suffering. So right now, Jesus Christ is with her. Period. That line is spoken with force. Whether hands are laid on her or not, prayers have already been prayed, and if the story of Jesus is true and it is His will to heal, then in some sense she is already healed. Then there's this push beyond linear time: He is outside time and sees every reality. So she is healed. Whether that healing manifests in this reality is almost beside the point, because the point is that healing is unto the glorification of Jesus, and suffering is also unto the glorification of Jesus. Sickness, hardship, endurance—these become a place to know the Father more, because He promises to be there and give peace beyond understanding. Then the end goal gets named plainly: salvation. Her salvation, her kids' salvation.

That's where another question comes in: would it be appropriate to pray that this situation brings them to their knees? The answer is yes, but with a check. God knows exactly what would bring them to their knees. She could be healed today and they might still turn away. Jesus died on the cross and people still reject Him. So seeing a healing manifest does not automatically change anything. That line answers the earlier question in a way that seems to satisfy it. The one who asked says, that completely answered my question.

### Identity and the Spirit

Then the conversation moves into identity and the spirit. There's a prayer suggested: God, open my eyes, remove the veil, let me see exactly how You see me. When He sees believers, He sees the spirit of life, righteousness that gives life to the mortal body. The spirit is the truest reality, more real than the physical realm, though people are bound by time and physical location. The body is dead unless it comes under the Spirit. Then it gets broken down plainly: you have soul, mind, will, emotions; you have flesh; you have spirit. The mind, will, and emotions set on the flesh cannot obey God. Set on the Spirit, they can.

Romans 8 gets opened and read out loud. The whole passage is brought in: the Spirit gives life, the flesh leads to death, those controlled by the sinful nature think about sinful things, those controlled by the Holy Spirit think about what pleases the Spirit, setting the mind on the Spirit leads to life and peace, the Spirit who raised Jesus from the dead lives in believers and gives life to mortal bodies. After it's read, the summary is made again: life comes to the mortal body when the mind, will, and emotions are set on the Spirit. The truest reality is the spirit, and the flesh has to come under it.

Then somebody asks the practical question that changes the tone again: how, as a simple guy, do I set my mind on the Spirit? That feels like one of the most grounded questions of the night. The answers come from Psalm 91 and John 15: dwell in the shelter of the Most High; abide in Him and let His words abide in you. Then it gets made even simpler: when I wake up and want to look at my phone, I put it down and set my attention on Christ. Someone else puts it even more bluntly: what does the world want? Your attention. Do the opposite. Worship gets named. Attention gets named. Laying down your life gets named. To be a good husband, lay down your life. To be a good friend, think of the other as higher than yourself and serve them. That's all it is.

Then one person goes lower and smaller in what feels like an attempt to answer the same question from another angle. Jesus called Himself a worm before death. If the Creator can become that small, then people can too. The whole walk is to live small, humble, low, with eyes on suffering, on the cross, on Jesus. Then the Holy Spirit consumes a person and they reflect God like a mirror. Someone thanks them because that is the practical answer they were looking for. Someone else adds a phrase passed along from a friend: attention is God's currency. That phrase clearly sticks with people. Another says that idea clicked only recently, after being frustrated in prayer, feeling unheard, asking why expectations weren't being met. Then comes the confrontation: what right do I have to expectations before my Creator? He already gave me life. He already sent His Son. If He didn't spare His Son, why would He withhold anything? The conclusion is that people are to expect nothing, die to self, live a life pleasing to God. It's one of those things heard a million times until suddenly it clicks, and when it clicks it is because the Holy Spirit lets you see it.

### Gold Like Transparent Glass

The conversation drifts into Revelation and New Jerusalem, but not in a scattered way. They're talking about what finally became real while reading it. There's wonder at the city being perfectly measured, all equal dimensions, a whole city rather than a castle. The image of pure gold like transparent glass hits someone, because even the most valuable things become see-through where God is the light. The point they pull from that is that if you are pursuing riches and valuable things, you are missing the point of life.

That leads into 1 Corinthians 3 being read. Christ is the only foundation. People build on it with gold, silver, jewels, wood, hay, straw. Fire will show what kind of work each person has done. Some work survives and receives reward. Some is burned up, though the person is saved, barely escaping through flames. Then the line that all together are the temple of God because the Spirit lives in them. The application made in the room is straightforward: whatever is built on the foundation God established is either going to burn up or bring reward in heaven. One person says with a kind of rough resolve that they are not going to spend the rest of their life gluing pipe together unless God wills it. That sounds like a vocational conviction surfacing out loud.

Then Revelation 22 gets read, especially the closing warning about adding to or taking away from the words of prophecy. Someone says the first thought that comes to mind is Jehovah's Witnesses. There's a reaction there, but it doesn't go much further.

### The Fear Under the Gathering

Toward the end, when the group is deciding whether to pray, the original purpose for gathering gets spoken more openly. One of us says he mostly wanted to create intentional space for everyone to come together and honor God. Then he admits one of his biggest fears: that this wasn't going to be as fun as D&D, that people wouldn't want to do it, that it would just look like him gathering everyone because of what he was going through. But that fear is exposed as pride, and also as distraction. He says God wanted to show the group that He was holding us in His hand, but we were too focused on creating our own world that He wasn't part of. God was challenging the group to let go of that and look around. He admits he ignored God for a few weeks, but God was patient. He wants prayer and repentance. There's gratitude too — for God, for the people in the room, for accountability now and in the future, especially accountability for getting out of his own way. He says the biggest challenge will be to shut up and let everyone else talk.

Someone circles back and asks for the full answer to the earlier question, and the answer is clear now: yes, the fear was that Bible study would not be as engaging as D&D, but it already has been. That seems to matter.

One more reflection comes in near the end. Someone says they like this because the more they talk about these things, the more it connects with what they've been reading in Ephesians, especially the idea that faith should be attractive rather than condemning. Talking about it together helps sharpen the words. Then it gets personal: faith has to be attractive because his wife is slightly apathetic, and cannot be forced into anything. The only option is to show and lead through faith. "That means I gotta be attractive." The room laughs a little there, but the point underneath it is serious and stays hanging in the air.

Then there's agreement to keep showing up. One person says they won't be there next week because they'll be in Ireland, but they'll be back the week after. And before all the rest of it disappears into the edges of the night, what remains is what the room kept circling from the beginning: God wants presence, not performance. Attention matters. Worship matters. Healing is real and still unanswered. Suffering is not outside Him. The flesh has to come under the Spirit. Questions stay open. Some things land. Some things just sit there. And the whole room feels like it is trying to learn how to become smaller, quieter, more honest, and more available to whatever God is doing.`,
    body: [
      { type: "lede", text: "This week really centered on one core idea: God doesn't just want to use us — He wants to give us Himself." },
      { type: "p", text: "We talked a lot about spiritual gifts, healing, prayer, discernment, and encouragement, but the strongest thread through all of it was intimacy with Jesus. The point isn't to become impressive, powerful, or gifted for our own sake. The point is to know Him, be close to Him, and be available to what He is already doing." },
      { type: "h", text: "Less of Me, More of Him" },
      { type: "p", text: "One of the most powerful themes was the shift from self-glorification to glorifying Jesus. That question came up clearly: How can I become less and He become more? That feels like a strong takeaway for all of us this week." },
      { type: "p", text: "When we live from that place, the pressure comes off. We don't have to force outcomes, carry spiritual weight on our own, or try to manufacture something. We just get to join the Father in what He is doing." },
      { type: "pullquote", text: "God doesn't just want to use us. He wants to give us Himself." },
      { type: "h", text: "On Healing and Unanswered Questions" },
      { type: "p", text: "We also talked about healing, especially around a family member of someone in the group, and the honest tension of asking why healing doesn't always happen the way we want or when we want. The conversation seemed to land on this: healing is God's will, but His ways are higher than ours, and His presence in suffering is just as real as His power in breakthrough." },
      { type: "p", text: "God knows exactly what He is doing, and His end goal is always deeper than what we can see in the moment." },
      { type: "h", text: "What Has Your Attention" },
      { type: "p", text: "Another big takeaway was from Romans 8: the mind set on the flesh is death, but the mind set on the Spirit is life and peace. The practical application was simple but strong — attention." },
      { type: "p", text: "What has our attention has more influence over us than we realize. Setting our minds on the Spirit can look as simple as choosing Jesus before distraction, worship before scrolling, prayer before noise." },
      { type: "pullquote", text: "Worship before scrolling. Prayer before noise." },
      { type: "h", text: "Called Out of the Worlds We Build" },
      { type: "p", text: "There was also a really honest and encouraging moment around one of us sharing his fear that gathering around God wouldn't be as engaging as D&D, and how God was exposing distraction and inviting him into something deeper." },
      { type: "p", text: "That felt like a reminder for everyone: sometimes God is calling us out of the worlds we build for ourselves and into real fellowship, repentance, and surrender." },
      { type: "h", text: "Reflection Questions" },
      { type: "p", text: "1. Am I seeking God mainly for what He can do, or because I want Him?" },
      { type: "p", text: "2. Where has my attention been going lately?" },
      { type: "p", text: "3. What would it look like for me to set my mind on the Spirit in a practical way this week?" },
      { type: "p", text: "4. Is there any area of my life where I still want my own glory more than Jesus' glory?" },
      { type: "p", text: "5. How is God inviting me to trust His presence, even in unanswered questions?" },
      { type: "h", text: "Practice for the Week" },
      { type: "p", text: "Before grabbing your phone in the morning, give Jesus your attention first. Even for just a few minutes. Sit with Him. Worship. Pray. Ask, Father, what are You doing today, and how can I be a part of it?" },
      { type: "h", text: "Closing Prayer" },
      { type: "p", text: "Jesus, teach us to want Your presence more than outcomes. Make us humble, available, and led by Your Spirit. Free us from striving, distraction, and self-glory. Set our minds on the Spirit and let our lives reflect You. Help us trust You in healing, suffering, waiting, and worship. Become greater in us as we become less." }
    ]
  }
];
